package guide.auto;

import core.AbstractPlayer;
import core.Game;
import games.GameType;

import java.util.List;

public class AutoGenerateDeck {

    private final static GameType gameType = GameType.Blackjack;

    public static boolean generate(List<AbstractPlayer> players, String strategy) {
        GameContext gameContext = new GameContext(gameType);
        while (true) {
            if (gameContext.isEnd()) {
                gameContext.exportJSON();
                break;
            }
            long seed = System.currentTimeMillis();
            Game game = Game.runOne(gameType, null, players, seed, false, null, null, 1);
            gameContext.execute(strategy, game, seed);
        }
        return true;
    }
}
