package guide.auto;

import core.AbstractPlayer;
import core.Game;
import games.GameType;

import java.util.ArrayList;
import java.util.List;

import static guide.auto.LoveLetterGameStrategy.tmpCardsForReserve;
import static guide.auto.LoveLetterGameStrategy.tmpCardsForReserveSwitch;


public class AutoGenerateDeck {

    /**
     * Generate JSON by searching matches
     * @param players MCTS players
     * @param strategy @see BlackjackGameStrategy.BlackjackStrategyEnum / LoveLetterGameStrategy.LoveLetterStrategyEnum
     * @param gameType @see GameType
     */
    public static void generate(List<AbstractPlayer> players, String strategy, GameType gameType) {
        GameContext gameContext = new GameContext(gameType);
        while (true) {
            if (gameContext.isEnd()) {
                gameContext.exportJSON();
                tmpCardsForReserveSwitch = false;
                break;
            }
            tmpCardsForReserveSwitch = true;
            tmpCardsForReserve = new ArrayList<>();
            long seed = System.currentTimeMillis();
            Game game = Game.runOne(gameType, null, players, seed, false, null, null, 1);
            gameContext.execute(strategy, game, seed);
        }
    }
}
